# +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
# | SIERRA : PHP Application Framework  http://code.google.com/p/sierra-php |
# +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
# |                   *** DO NOT EDIT THIS FILE ***                         |
# |                                                                         |
# | This dtd source file was generated by the SIERRA Entity modeler.        |
# | according to the entity model described in the source file listed below.|
# | This file will be overwritten each time a change to that file is made.  |
# +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+
# entity model source file: {$entityModelPath}


